export const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FAILURE = 'FETCH_MESSAGES_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const FETCH_CHAT_SUCCESS = 'FETCH_CHAT_SUCCESS';
export const FETCH_CHAT_FAILURE = 'FFETCH_CHAT_FAILURE';
export const FETCH_CHANGE_CHAT_STATUS = 'FETCH_CHANGE_CHAT_STATUS';
export const CHANGE_CHAT_STATUS = 'CHANGE_CHAT_STATUS';
export const GET_CHAT = 'GET_CHAT';
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
export const FETCH_ADD_NEW_MESSAGE = 'FETCH_ADD_NEW_MESSAGE';
export const FETCH_AUTO_COMPLETE_REQUEST = 'FETCH_AUTO_COMPLETE_REQUEST';
export const FETCH_AUTO_COMPLETE_SUCCESS = 'FETCH_AUTO_COMPLETE_SUCCESS';
export const FETCH_AUTO_COMPLETE_FAILURE = 'FETCH_AUTO_COMPLETE_FAILURE';

